Merge feature/refactor into main (#560)
Co-authored-by: T N <taichi6930.tokyojihen.pelusa@gmail.com>

diff --git a/.github/workflows/race-schedule.yml b/.github/workflows/race-schedule.yml
--- a/.github/workflows/race-schedule.yml
+++ b/.github/workflows/race-schedule.yml
@@ -1,9 +1,9 @@
-name: Race Schedule NAR
+name: Race Schedule
 
 on:
   schedule:
-    # 日本時間0時と12時（JST0時=UTC15時, JST12時=UTC3時）
-    - cron: '0 15,3 * * *'
+    # 日本時間の毎日6,16,22時に実行
+    - cron: '0 7,13,21 * * *'
   workflow_dispatch:
     inputs:
       start-date:
@@ -22,47 +22,47 @@ permissions:
 
 jobs:
   set-dates:
-      runs-on: ubuntu-latest
-      outputs:
-        start-date: ${{ steps.set-dates.outputs.start-date }}
-        finish-date: ${{ steps.set-dates.outputs.finish-date }}
-      steps:
-        - name: Outputを設定
-          id: set-dates
-          run: |
-            # 日付を計算、デフォルトは昨日から2日後
-            startDate="${{ github.event.inputs.start-date }}"
-            finishDate="${{ github.event.inputs.finish-date }}"
+    runs-on: ubuntu-latest
+    outputs:
+      start-date: ${{ steps.set-dates.outputs.start-date }}
+      finish-date: ${{ steps.set-dates.outputs.finish-date }}
+    steps:
+      - name: Outputを設定
+        id: set-dates
+        run: |
+          # 日付を計算、デフォルトは昨日から2日後
+          startDate="${{ github.event.inputs.start-date }}"
+          finishDate="${{ github.event.inputs.finish-date }}"
 
-            # 入力がない場合のデフォルト設定
-            if [ -z "$startDate" ]; then
-              startDate=$(date -d "yesterday" +"%Y-%m-%d")
-            fi
-            if [ -z "$finishDate" ]; then
-              finishDate=$(date -d "+2 days" +"%Y-%m-%d")
-            fi
+          # 入力がない場合のデフォルト設定
+          if [ -z "$startDate" ]; then
+            startDate=$(date -d "yesterday" +"%Y-%m-%d")
+          fi
+          if [ -z "$finishDate" ]; then
+            finishDate=$(date -d "+1 day" +"%Y-%m-%d")
+          fi
 
-            # GITHUB_OUTPUTを使って出力設定
-            echo "start-date=$startDate" >> $GITHUB_OUTPUT
-            echo "finish-date=$finishDate" >> $GITHUB_OUTPUT
+          # GITHUB_OUTPUTを使って出力設定
+          echo "start-date=$startDate" >> $GITHUB_OUTPUT
+          echo "finish-date=$finishDate" >> $GITHUB_OUTPUT
 
   health-check:
-      runs-on: ubuntu-latest
-      steps:
-        - name: Check out repository
-          uses: actions/checkout@v4
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
 
-        - name: Start server in background
-          run: |
-            health_check_response=$(curl -s -o /dev/null -w "%{http_code}" ${API_PRODUCTION_URL}/health)
+      - name: Start server in background
+        run: |
+          health_check_response=$(curl -s -o /dev/null -w "%{http_code}" ${API_PRODUCTION_URL}/health)
 
-            # レスポンスチェック
-            if [[ "$health_check_response" != "200" ]]; then
-              echo "❌ POST request failed with status code $health_check_response"
-              exit 1
-            fi
+          # レスポンスチェック
+          if [[ "$health_check_response" != "200" ]]; then
+            echo "❌ POST request failed with status code $health_check_response"
+            exit 1
+          fi
 
-  update-nar-race-data:
+  update-race-data:
     needs: [set-dates, health-check]
     runs-on: ubuntu-latest
     steps:
@@ -83,7 +83,7 @@ jobs:
             -d "{
                   \"startDate\": \"$startDate\",
                   \"finishDate\": \"$finishDate\",
-                  \"raceType\": [\"nar\"]
+                  \"raceType\": [\"overseas\", \"autorace\", \"boatrace\"]
                 }")
 
           # レスポンスチェック
@@ -92,8 +92,8 @@ jobs:
             exit 1
           fi
 
-  update-nar-race-calendar:
-    needs: [set-dates, update-nar-race-data]
+  update-race-calendar:
+    needs: [set-dates, update-race-data]
     runs-on: ubuntu-latest
     steps:
       - name: Check out repository
@@ -112,11 +112,11 @@ jobs:
             -d "{
                   \"startDate\": \"$startDate\",
                   \"finishDate\": \"$finishDate\",
-                  \"raceType\": [\"nar\"]
+                  \"raceType\": [\"nar\", \"overseas\", \"autorace\", \"boatrace\"]
                 }")
 
-            # レスポンスチェック
-            if [[ "$update_race_calendar_response" != "200" ]]; then
-              echo "❌ POST request failed with status code $update_race_calendar_response"
-              exit 1
-            fi
+          # レスポンスチェック
+          if [[ "$update_race_calendar_response" != "200" ]]; then
+            echo "❌ POST request failed with status code $update_race_calendar_response"
+            exit 1
+          fi
